version: '3.9'

services:
  redis:
    image: redis
    command: redis-server
    ports:
      - "6379:6379"
  postgres:
    image: postgres
    environment:
      - POSTGRES_USER=softuni
      - POSTGRES_PASSWORD=softuni
      - POSTGRES_DB=wonderlanders_db
    ports:
      - "5432:5432"
  web:
    image: elly2chan/wonderlanders
    build: .
    restart: always
    command: gunicorn wonderlanders.wsgi:application --bind 0.0.0.0:8000
    env_file:
      - envs/.env.prod
    ports:
      - "8000:8000"
    volumes:
      - ./staticfiles/:/tmp/wonderlanders/staticfiles
    depends_on:
      - postgres
      - redis
  nginx:
    image: nginx
    ports:
      - "81:80"
      - "443:443"
    volumes:
      - ./staticfiles:/home/app/web/staticfiles
      - ./nginx/conf.d:/etc/nginx/conf.d
      - ./nginx/logs:/var/log/nginx
      - ./certbot/www:/var/www/certbot/:ro
      - ./certbot/conf/:/etc/nginx/ssl/:ro
    depends_on:
      - web