version: '3.9'

services:
  redis:
    image: redis
    command: redis-server
    ports:
      - "6379:6379"
  postgres:
    image: postgres
    environment:
      - POSTGRES_USER=softuni
      - POSTGRES_PASSWORD=softuni
      - POSTGRES_DB=wonderlanders_db
    ports:
      - "5432:5432"
  web:
    build: .
    restart: always
    command: python manage.py runserver 0.0.0.0:8000
    env_file:
      - envs/.env
    ports:
      - "8000:8000"
    volumes:
      - .:/code
    depends_on:
      - postgres
      - redis