# Generated by Django 4.1.3 on 2022-11-24 18:19

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import wonderlanders.core.validators
import wonderlanders.posts.models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('posts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(error_messages={'max_length': 'Post title must be a maximum of 20 characters.', 'min_length': 'Post title must be at least 3 characters long.'}, max_length=20, validators=[django.core.validators.MinLengthValidator(3), wonderlanders.core.validators.name_and_title_validator])),
                ('image', models.ImageField()),
                ('destination', models.CharField(error_messages={'max_length': 'Destination must be a maximum of 30 characters.', 'min_length': 'Destination must be at least 3 characters long.'}, max_length=30, validators=[django.core.validators.MinLengthValidator(3)])),
                ('description', models.CharField(error_messages={'max_length': 'Description must be a maximum of 550 characters.', 'min_length': 'Description must be at least 5 characters long.'}, max_length=550, validators=[django.core.validators.MinLengthValidator(5)])),
            ],
        ),
        migrations.CreateModel(
            name='PostComment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.CharField(error_messages={'max_length': 'Comment must be a maximum of 300 characters.'}, max_length=300)),
                ('publication_datetime', models.DateTimeField(auto_now_add=True)),
                ('post', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='posts.post')),
                ('user', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='PostCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(error_messages={'max_length': 'Category title must be a maximum of 15 characters.', 'min_length': 'Category title must be at least 3 characters long.'}, max_length=15, validators=[django.core.validators.MinLengthValidator(3), wonderlanders.core.validators.name_and_title_validator])),
                ('slug', models.SlugField(blank=True, unique=True)),
                ('user', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Post Categories',
            },
        ),
        migrations.AddField(
            model_name='post',
            name='category',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='posts.postcategory'),
        ),
        migrations.AddField(
            model_name='post',
            name='user',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
