# Generated by Django 4.1.3 on 2022-11-24 18:22

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import wonderlanders.core.validators
import wonderlanders.products.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(error_messages={'max_length': 'Category title must be a maximum of 15 characters.', 'min_length': 'Category title must be at least 3 characters long.'}, max_length=15, validators=[django.core.validators.MinLengthValidator(3), wonderlanders.core.validators.name_and_title_validator])),
                ('slug', models.SlugField(blank=True, unique=True)),
                ('user', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'product categories',
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(error_messages={'max_length': 'Product title must be a maximum of 12 characters.', 'min_length': 'Product title must be at least 3 characters long.'}, max_length=12, validators=[django.core.validators.MinLengthValidator(3), wonderlanders.core.validators.name_and_title_validator])),
                ('image', models.ImageField()),
                ('price', models.FloatField()),
                ('destination', models.CharField(blank=True, error_messages={'max_length': 'Destination must be a maximum of 17 characters.', 'min_length': 'Destination must be at least 3 characters long.'}, max_length=17, validators=[django.core.validators.MinLengthValidator(3), wonderlanders.core.validators.name_and_title_validator])),
                ('category', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='products.productcategory')),
                ('user', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
