# Generated by Django 4.1.3 on 2022-11-28 11:21

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_create_product_and_category_models'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='image',
        ),
        migrations.AddField(
            model_name='product',
            name='photo',
            field=cloudinary.models.CloudinaryField(default=0, max_length=255),
            preserve_default=False,
        ),
    ]
