# Generated by Django 4.1.3 on 2022-11-24 18:23

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import wonderlanders.core.validators
import wonderlanders.store.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('store', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_date', models.DateTimeField(auto_now_add=True)),
                ('first_name', models.CharField(error_messages={'max_length': 'First name must be a maximum of 250 characters.', 'min_length': 'First name must be at least 3 characters long.'}, max_length=30, validators=[django.core.validators.MinLengthValidator(3), wonderlanders.core.validators.name_and_title_validator])),
                ('last_name', models.CharField(error_messages={'max_length': 'Last name must be a maximum of 250 characters.', 'min_length': 'Last name must be at least 3 characters long.'}, max_length=30, validators=[django.core.validators.MinLengthValidator(3), wonderlanders.core.validators.name_and_title_validator])),
                ('postal_code', models.CharField(error_messages={'max_length': 'Postal code must be a maximum of 10 digits.', 'min_length': 'Postal code must be at least 3 digits long.'}, max_length=10, validators=[django.core.validators.MinLengthValidator(4), wonderlanders.core.validators.only_digits_validator])),
                ('email', models.EmailField(error_messages={'max_length': 'Email must be a maximum of 250 characters.', 'min_length': 'Email must be at least 3 characters long.'}, max_length=250, validators=[django.core.validators.MinLengthValidator(3)])),
                ('address', models.CharField(error_messages={'max_length': 'Address must be a maximum of 50 characters.', 'min_length': 'Address must be at least 5 characters long.'}, max_length=50, validators=[django.core.validators.MinLengthValidator(5)])),
                ('city', models.CharField(error_messages={'max_length': 'City must be a maximum of 30 characters.', 'min_length': 'City must be at least 3 characters long.'}, max_length=30, validators=[django.core.validators.MinLengthValidator(3), wonderlanders.core.validators.name_and_title_validator])),
                ('country', models.CharField(choices=[('bulgaria', 'Bulgaria'), ('serbia', 'Serbia'), ('greece', 'Greece'), ('romania', 'Romania'), ('macedonia', 'Macedonia')], default=wonderlanders.store.models.Country['bulgaria'], max_length=9)),
                ('phone', models.CharField(error_messages={'max_length': 'Phone must be a maximum of 15 characters.', 'min_length': 'Phone must be at least 5 digits long.'}, max_length=15, validators=[django.core.validators.MinLengthValidator(5), wonderlanders.core.validators.only_digits_validator])),
                ('order_total_price', models.FloatField(blank=True, null=True)),
                ('order_products_quantity', models.IntegerField(blank=True, null=True)),
                ('user', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
